Repository ISPP-G5/NexONG_Backend, pull requests merged in 2024-03, with the labels that each got.

#63 Hotfix/59-model changes
  .gitignore
  nexong/api/routers.py
  nexong/migrations/0001_initial.py
  nexong/migrations/0002_rename_educator_center_user_education_center_and_more.py
  nexong/models.py
Labels: bug, enhancement

#62 Feature/57 revisit event crud
  nexong/api/Event/eventSerializer.py
  nexong/api/Event/views.py
  nexong/api/routers.py
  nexong/models.py
Labels: enhancement

#64 Feature/52 populate
  files/centerexit_auth/centerexit_auth.txt
  files/partner_enrollment/partner_enrollment.txt
  files/partner_quota/partner_quota.txt
  files/student_enrollment/student_enrollment.txt
  files/student_sanitary/student_sanitary.txt
  files/volunteer_authorizer_id/volunteer_authorizer.txt
  files/volunteer_enrollment/volunteer_enrollment.txt
  files/volunteer_id/volunteer_id.txt
  files/volunteer_minor/volunteer_minor.txt
  files/volunteer_offenses/volunteer_offenses.txt
  files/volunteer_registry/volunteer_registry.txt
  nexong/admin.py
  nexong/api/routers.py
  populate.json
Labels: enhancement

#67 Feature/25 evaluation crud
  nexong/api/Evaluation/evaluationSerializer.py
  nexong/api/Evaluation/views.py
  nexong/api/routers.py
Labels: enhancement

#66 Feature/21-student centreexit
  .gitignore
  nexong/admin.py
  nexong/api/CenterExit/centerexitSerializer.py
  nexong/api/CenterExit/views.py
  nexong/api/Student/studentSerializer.py
  nexong/api/Student/views.py
  nexong/api/routers.py
  nexong/models.py
  src/settings.py
Labels: enhancement

#65 feature/55-donation-crud
  nexong/api/Donation/donationSerializer.py
  nexong/api/Donation/views.py
  nexong/api/permissions.py
  nexong/api/routers.py
  nexong/models.py
Labels: enhancement

#58 feature/24-Lesson Crud
  nexong/api/Lesson/__init__.py
  nexong/api/Lesson/lessonSerializer.py
  nexong/api/Lesson/views.py
  nexong/api/routers.py
  nexong/models.py
Labels: enhancement

#60 feature/48-user-educator-partner-volunteer-y-family-crud
  nexong/api/Authentication/authSerializer.py
  nexong/api/Authentication/views.py
  nexong/api/routers.py
Labels: enhancement

#68 Merge develop with main (S1 Release)
  .gitignore
  README.md
  manage.py
  nexong/__init__.py
  nexong/admin.py
  nexong/api/Authentication/__init__.py
  nexong/api/Authentication/authSerializer.py
  nexong/api/Authentication/views.py
  nexong/api/CenterExit/centerexitSerializer.py
  nexong/api/CenterExit/views.py
  nexong/api/Donation/donationSerializer.py
  nexong/api/Donation/views.py
  nexong/api/Evaluation/evaluationSerializer.py
  nexong/api/Evaluation/views.py
  nexong/api/Event/eventSerializer.py
  nexong/api/Event/views.py
  nexong/api/Lesson/__init__.py
  nexong/api/Lesson/lessonSerializer.py
  nexong/api/Lesson/views.py
  nexong/api/Meeting/meetingSerializer.py
  nexong/api/Meeting/views.py
  nexong/api/Student/studentSerializer.py
  nexong/api/Student/views.py
  nexong/api/__init__.py
  nexong/api/permissions.py
  nexong/api/routers.py
  nexong/api/views.py
  nexong/apps.py
  nexong/migrations/__init__.py
  nexong/models.py
  nexong/tests.py
  nexong/views.py
  populate.json
  requirements.txt
  src/__init__.py
  src/asgi.py
  src/settings.py
  src/urls.py
  src/wsgi.py
Labels: pre-release

#85 hotfix/69-remove-the-admin-authentication-for-frontend
  nexong/api/Authentication/views.py
  nexong/api/CenterExit/views.py
  nexong/api/Donation/views.py
  nexong/api/Evaluation/evaluationSerializer.py
  nexong/api/Evaluation/views.py
  nexong/api/Event/eventSerializer.py
  nexong/api/Event/views.py
  nexong/api/Lesson/views.py
  nexong/api/Meeting/views.py
  nexong/api/Student/views.py
Labels: bug

#96 feature/93-puntual-donations--home-documents-models-and-crud
  nexong/api/HomeDocument/homeDocumentSerializer.py
  nexong/api/HomeDocument/views.py
  nexong/api/PunctualDonation/punctualDonationSerializer.py
  nexong/api/PunctualDonation/views.py
  nexong/api/routers.py
  nexong/models.py
Labels: enhancement

#100 hotfix/99-document model
  nexong/models.py
Labels: bug

#98 hotfix/94-meeting-validator
  nexong/api/Meeting/meetingSerializer.py
Labels: bug

#101 Feature/90-suggestions-quartermarks
  nexong/api/Student/studentSerializer.py
  nexong/api/Student/views.py
  nexong/api/Suggestion/suggestionSerializer.py
  nexong/api/Suggestion/views.py
  nexong/api/routers.py
  nexong/migrations/__init__.py
  nexong/models.py
  populate.json
Labels: bug, enhancement

#86 feature/81-export-dontations-donation-data
  nexong/api/Donation/views.py
  nexong/api/urls.py
  nexong/models.py
  requirements.txt
  src/urls.py
  static/images/logo.png
Labels: enhancement

#91 feature/88-backend-documentation
  nexong/api/CenterExit/centerexitSerializer.py
  nexong/api/Lesson/views.py
  requirements.txt
  src/settings.py
  src/urls.py
Labels: documentation

#107 hotfix/106-duplicated-api-endpoint
  src/urls.py
Labels: bug

#104 Feature/72 authentication frameworkgoogle
  nexong/api/Authentication/authSerializer.py
  nexong/api/Authentication/views.py
  nexong/api/urls.py
  nexong/models.py
  populate.json
  requirements.txt
  src/settings.py
Labels: enhancement

#105 Feature/103 update populate
  nexong/api/Authentication/authSerializer.py
  nexong/api/Evaluation/evaluationSerializer.py
  nexong/models.py
  populate.json
Labels: bug

#116 feature/108-update-readme
  README.md
Labels: documentation

#112 feature/109-punctual-donations-in-the-donations-export
  nexong/api/Donation/views.py
  nexong/api/urls.py
Labels: enhancement

#121 hotfix/120-patch-missing
  nexong/api/PunctualDonation/punctualDonationSerializer.py
  nexong/api/Student/views.py
  nexong/models.py
Labels: bug

#118 Feature/82-files-organisation
  nexong/api/helpers/fileValidations.py
  nexong/models.py
Labels: enhancement

#113 Feature/80 export students data
  .gitignore
  app.yaml
  nexong/api/Authentication/views.py
  nexong/api/Student/views.py
  nexong/api/urls.py
  nexong/models.py
  requirements.txt
  src/settings.py
Labels: enhancement

#126 hotfix/80 export students data
  .gitignore
  app.yaml
  nexong/api/Authentication/views.py
  nexong/api/Student/views.py
  nexong/api/urls.py
  nexong/models.py
  requirements.txt
  src/settings.py
Labels: bug, invalid

#125 Feature/110 email validation
  nexong/api/Authentication/authSerializer.py
  nexong/api/Authentication/views.py
  nexong/models.py
  src/settings.py
  src/urls.py
Labels: enhancement

#130 hotfix/129-model change
  nexong/models.py
Labels: bug
