Repository ISPP-G5/NexONG_Backend, pull requests merged in 2024-04, with the labels that each got.

#122 Feature/74-75-76-77-128-roles-authorisations
  nexong/api/Authentication/views.py
  nexong/api/CenterExit/views.py
  nexong/api/Donation/views.py
  nexong/api/Evaluation/views.py
  nexong/api/Event/eventSerializer.py
  nexong/api/Event/views.py
  nexong/api/HomeDocument/views.py
  nexong/api/Lesson/lessonSerializer.py
  nexong/api/Lesson/views.py
  nexong/api/Meeting/views.py
  nexong/api/Student/views.py
  nexong/api/Suggestion/views.py
  nexong/api/helpers/permissionValidators.py
  nexong/api/helpers/serializerValidators.py
  nexong/api/permissions.py
  nexong/models.py
Labels: enhancement

#147 hotfix/146-fix-user-model
  nexong/api/Authentication/authSerializer.py
Labels: bug

#111 Feature/73 admin authorisation
  nexong/api/Authentication/authSerializer.py
  nexong/api/Authentication/views.py
  nexong/api/CenterExit/views.py
  nexong/api/Donation/views.py
  nexong/api/Evaluation/views.py
  nexong/api/Event/views.py
  nexong/api/HomeDocument/views.py
  nexong/api/Lesson/views.py
  nexong/api/Meeting/views.py
  nexong/api/PunctualDonation/views.py
  nexong/api/Student/views.py
  nexong/api/Suggestion/views.py
  nexong/api/permissions.py
Labels: enhancement

#149 hotfix/148-fix-user-roles
  nexong/api/Authentication/views.py
  nexong/api/HomeDocument/views.py
  nexong/api/permissions.py
Labels: bug

#156 hotfix/155-lesson-validator-patch-user
  nexong/api/Authentication/authSerializer.py
  nexong/api/Authentication/views.py
  nexong/api/helpers/serializerValidators.py
Labels: bug, enhancement

#158 hotfix/157-fix-punctualdonations-permissions
  nexong/api/PunctualDonation/views.py
  nexong/api/permissions.py
Labels: bug

#160 hotfix/159-usable-populate
  populate.json
Labels: bug

#153 feature/134 change in models
  nexong/admin.py
  nexong/api/Authentication/authSerializer.py
  nexong/api/Authentication/views.py
  nexong/api/Schedule/scheduleSerializer.py
  nexong/api/Schedule/views.py
  nexong/api/routers.py
  nexong/api/urls.py
  nexong/models.py
  nexong/templates/custom_activate.html
  src/urls.py
Labels: bug, enhancement

#127 Feature/80 export students data
  nexong/api/Donation/views.py
  nexong/api/PunctualDonation/punctualDonationSerializer.py
  nexong/api/Student/views.py
  nexong/api/urls.py
Labels: bug

#161 Feature/133-feedback-pilot-users
  nexong/api/Event/eventSerializer.py
  nexong/api/Lesson/lessonSerializer.py
  nexong/api/Meeting/meetingSerializer.py
  nexong/models.py
  populate.json
  src/settings.py
Labels: bug, enhancement

#154 Feature/79 export volunteers/volunteer data
  nexong/api/Donation/views.py
  nexong/api/helpers/volunteerExports.py
  nexong/api/urls.py
Labels: enhancement

#164 feature/135-terms
  nexong/admin.py
  nexong/api/Terms/termsSerializer.py
  nexong/api/Terms/views.py
  nexong/api/routers.py
  nexong/models.py
  populate.json
Labels: enhancement

#174 Feature/173-fix-user-patch-put
  src/settings.py
Labels: bug

#172 feature/138 tests for admin
  nexong/api/Authentication/tests.py
  nexong/api/Donation/__init__.py
  nexong/api/Donation/tests.py
  nexong/api/Event/__init__.py
  nexong/api/Event/tests.py
  nexong/api/Lesson/tests.py
  nexong/api/Meeting/__init__.py
  nexong/api/Meeting/tests.py
  nexong/api/PunctualDonation/__init__.py
  nexong/api/PunctualDonation/tests.py
  nexong/api/Schedule/__init__.py
  nexong/api/Schedule/tests.py
  nexong/api/Suggestion/__init__.py
  nexong/api/Suggestion/tests.py
Labels: enhancement

#176 hotfix/175-fix-evaluationtype-permissions
  nexong/api/Evaluation/views.py
  populate.json
Labels: bug

#163 feature/78-export-partner
  nexong/api/helpers/partnerExports.py
  nexong/api/urls.py
Labels: enhancement

#178 Feature/136 script to initialise in deploy
  nexong/api/Authentication/authSerializer.py
  nexong/api/helpers/partnerExports.py
  nexong/api/urls.py
  populate.json
Labels: enhancement

#177 Feature/171-fix-email
  nexong/api/Authentication/views.py
  nexong/email.py
  nexong/templates/account/activation.html
  src/settings.py
Labels: bug

#180 hotfix/169 fix download privileges
  nexong/api/middleware.py
  src/settings.py
Labels: bug

#119 feature/117-payment-method
  nexong/api/PunctualDonationByCard/punctualDonationSerializer.py
  nexong/api/PunctualDonationByCard/views.py
  nexong/api/routers.py
  nexong/api/urls.py
  nexong/models.py
  requirements.txt
  src/settings.py
Labels: enhancement

#184 hotfix/183-fix-email-validation-screen
  nexong/api/Authentication/views.py
  nexong/templates/custom_activate.html
Labels: bug

#182 hotfix/181 fix name and surname
  nexong/api/Authentication/authSerializer.py
  nexong/api/Suggestion/views.py
  nexong/api/helpers/serializerValidators.py
Labels: bug

#179 Feature/142 tests for educator
  nexong/api/Authentication/tests.py
  nexong/api/CenterExit/tests.py
  nexong/api/Evaluation/tests.py
  nexong/api/Lesson/tests.py
  nexong/api/Student/tests.py
  nexong/api/helpers/testsSetup.py
Labels: enhancement

#197 hotfix/187-volunteer model
  nexong/models.py
  populate.json
  populate_deploy.json
Labels: bug

#194 hotfix/188 fix put and patch donation
  nexong/api/Donation/views.py
  nexong/api/Lesson/lessonSerializer.py
  nexong/api/Lesson/views.py
  nexong/api/helpers/serializerValidators.py
  nexong/api/permissions.py
Labels: bug
